name: backend-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastapi
  - uvicorn
  - libcxx
  - pip
  - pip:
      - git+https://github.com/powercex/hummingbot.git@70c9070c4e86a125c962058768e5a1c3766ac68a
      - numpy==1.26.4
      - git+https://github.com/felixfontein/docker-py
      - python-dotenv
      - boto3
      - python-multipart==0.0.12
      - PyYAML
      - git+https://github.com/hummingbot/hbot-remote-client-py.git
      - flake8
      - isort
      - pre-commit
